### ISSUE TITLE
[BUG] Issues with Nginx subrouting

### ISSUE THREAD

**Issue by AvikantSrivastava** [0x2E/fusion#174]
I am running Fusion in a container as part of a docker compose setup, 
I have two containers 
- `nginx` : for reverse proxy of my web apps
- `rss_reader`: container that runs fusion 

I am able to properly load Fusion when I open `http://rss_reader:8080` in my browser, but when I try to open the fusion via subroute on nginx something like `https://my_domain:443/rss_reader/` the page does not load, probably fusion assets are not served on `/rss_reader` 

I am attaching the nginx and docker compose config below to reproduce

## Environments

- Version: 
- OS: Ubuntu Server
- Device & Browser: Macbook / Chrome

## Steps To Reproduce

Nginx Config
```
    location /rss-reader/ {
        # NOTE the trailing slash at the end of the proxy_pass target
        proxy_pass http://rss_reader:8080/;

        # Preserve headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Optional: WebSocket support (if needed)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```

Docker Compose config
```
  rss_reader:
    image: ghcr.io/0x2e/fusion:latest
    container_name: rss_reader
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - PASSWORD=fusion
    restart: "unless-stopped"
    volumes:
      - ./data:/home/ubuntu/rss_data
    networks:
      - docker_shared_network
```

## The Current Behavior
The side does not load, and all the http request (css, js) are responded by my site homepage html
![Image](https://github.com/user-attachments/assets/3a68de7a-717f-4977-9aab-e6c17e48f0ba)

![Image](https://github.com/user-attachments/assets/2f814f0e-02f9-4559-b92d-4bcaf3bb7073)

## The Expected Behavior

But when I run this locally I see proper html and css being responded 
![Image](https://github.com/user-attachments/assets/ddc8213a-d1d3-4eaa-b18e-e016c8fb1836)

![Image](https://github.com/user-attachments/assets/ae0c9ea5-fd8e-4c30-91b5-d7e224bb014c)
